// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/frapposelli/wwhrd"
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/sqs/goreturns"
	_ "gotest.tools/gotestsum"
	_ "mvdan.cc/gofumpt"
)